[rollinghall]
title = "멜론 티켓 ─ 롤링홀"
url = "https://ticket.melon.com/place/index.htm?placeId=43"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[west-bridge]
title = "멜론 티켓 ─ 웨스트브릿지"
url = "https://ticket.melon.com/place/index.htm?placeId=293"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[prismhall]
title = "멜론 티켓 ─ 프리즘홀"
url = "https://ticket.melon.com/place/index.htm?placeId=731"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[veloso]
title = "멜론 티켓 ─ 벨로주"
url = "https://ticket.melon.com/place/index.htm?placeId=12"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[gurumare]
title = "멜론 티켓 ─ 구름아래소극장"
url = "https://ticket.melon.com/place/index.htm?placeId=724"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[sangsangmadang_hd]
title = "멜론 티켓 ─ KT&G 상상마당 라이브홀"
url = "https://ticket.melon.com/place/index.htm?placeId=913"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[sangsangmadang_dc]
title = "멜론 티켓 ─ KT&G 상상마당 대치아트홀"
url = "https://ticket.melon.com/place/index.htm?placeId=904"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[cjazit]
title = "멜론 티켓 ─ CJ아지트 광흥창"
url = "https://ticket.melon.com/place/index.htm?placeId=329"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[yes24livehall]
title = "멜론 티켓 ─ 예스24 라이브홀"
url = "https://ticket.melon.com/place/index.htm?placeId=11"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[nestnada]
title = "멜론 티켓 ─ 네스트 나다"
url = "https://ticket.melon.com/place/index.htm?placeId=546"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[nodeul]
title = "멜론 티켓 ─ 노들섬"
url = "https://ticket.melon.com/place/index.htm?placeId=902"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[wadiz]
title = "멜론 티켓 ─ 공간 와디즈"
url = "https://ticket.melon.com/place/index.htm?placeId=1083"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[bbangyatv]
title = "멜론 티켓 ─ 빵야TV"
url = "https://ticket.melon.com/place/index.htm?placeId=1035"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[danchutv]
title = "멜론 티켓 ─ 단추TV"
url = "https://ticket.melon.com/place/index.htm?placeId=1055"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"

[artistscard]
title = "멜론 티켓 ─ 아티스츠카드 앱＆웹 서비스"
url = "https://ticket.melon.com/place/index.htm?placeId=1074"
entrySelector = "tbody[id='list_list'] tr"
titleSelector = "span.show_title"
linkSelector = "span.show_title a"
contentSelector = "td.show_date"
imageSelector = "div.thumb_90x125.img a img"
waitUntil = "networkidle"


